"""Initial tables: users, items, user_items, combats, stamina_logs

Revision ID: b1d6e3a586c8
Revises: 
Create Date: 2026-03-13 18:08:54.710980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1d6e3a586c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player1_hp', sa.Integer(), nullable=True),
    sa.Column('player2_hp', sa.Integer(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combats_id'), 'combats', ['id'], unique=False)
    op.create_index(op.f('ix_combats_is_active'), 'combats', ['is_active'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('slot', sa.String(length=50), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('buy_price', sa.Integer(), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soulbound', sa.Boolean(), nullable=True),
    sa.Column('tradeable', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('character_class', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('spirit', sa.Integer(), nullable=True),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('mana', sa.Integer(), nullable=True),
    sa.Column('max_mana', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('max_stamina', sa.Integer(), nullable=True),
    sa.Column('stamina_last_regen', sa.TIMESTAMP(), nullable=True),
    sa.Column('fatigue_state', sa.String(length=20), nullable=True),
    sa.Column('fatigue_penalty', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stamina_warnings_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('story_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('in_combat', sa.Boolean(), nullable=True),
    sa.Column('combat_opponent_id', sa.Integer(), nullable=True),
    sa.Column('inventory_slots', sa.Integer(), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_buffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_debuffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_index(op.f('ix_users_in_combat'), 'users', ['in_combat'], unique=False)
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=False)
    op.create_table('stamina_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('stamina_change', sa.Integer(), nullable=False),
    sa.Column('stamina_before', sa.Integer(), nullable=False),
    sa.Column('stamina_after', sa.Integer(), nullable=False),
    sa.Column('warning_triggered', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vk_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamina_logs_id'), 'stamina_logs', ['id'], unique=False)
    op.create_index(op.f('ix_stamina_logs_timestamp'), 'stamina_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stamina_logs_vk_id'), 'stamina_logs', ['vk_id'], unique=False)
    op.create_table('user_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('equipped', sa.Boolean(), nullable=True),
    sa.Column('bonus_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enchantment_level', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['vk_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_items_id'), 'user_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_items_vk_id'), 'user_items', ['vk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_items_vk_id'), table_name='user_items')
    op.drop_index(op.f('ix_user_items_id'), table_name='user_items')
    op.drop_table('user_items')
    op.drop_index(op.f('ix_stamina_logs_vk_id'), table_name='stamina_logs')
    op.drop_index(op.f('ix_stamina_logs_timestamp'), table_name='stamina_logs')
    op.drop_index(op.f('ix_stamina_logs_id'), table_name='stamina_logs')
    op.drop_table('stamina_logs')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_index(op.f('ix_users_location'), table_name='users')
    op.drop_index(op.f('ix_users_in_combat'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_combats_is_active'), table_name='combats')
    op.drop_index(op.f('ix_combats_id'), table_name='combats')
    op.drop_table('combats')
    # ### end Alembic commands ###
